version: '3.3'

services:
  postgis:
    image: postgis/postgis:14-3.2
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: 'exit 0'
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  minio:
    image: minio/minio
    restart: always
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - storage-minio:/data
    command: server --address ":9000" --console-address ":9090" /data
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    logging:
      driver: "none" # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  mapstoriesadmin:
    image: ghcr.io/reedu-reengineering-education/insta-admin:main
    restart: always
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    env_file:
      - './.adminenv'
    ports:
      - '3001:3001'
    networks:
      - internal

volumes:
  storage-minio:

networks:
  internal: