version: '3.3'

services:
  postgis:
    image: postgis/postgis:14-3.2
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: 'exit 0'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - storage-minio:/data
    command: server --address ":9000" --console-address ":9090" /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/mapstories20;
      /usr/bin/mc policy set public myminio/mapstories20;
      exit 0;
      "

volumes:
  storage-minio:
