version: '3.3'

services:
  postgis:
    image: postgis/postgis:14-3.2
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: 'exit 0'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  minio:
    image: minio/minio
    restart: always
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - storage-minio:/data
    command: server --address ":9000" --console-address ":9090" /data
volumes:
  storage-minio:
