-- Placeholder for a migration.sql file that was applied to this database but
-- never committed to the repo. Its schema change was fully undone by the very
-- next migration (20260904122827_revert_language_label_and_flag) — the current
-- schema.prisma has no language label/flag fields, confirming the net effect
-- of the two migrations together is a no-op. Recreated as an empty migration
-- so the local migrations directory matches the applied migration history in
-- `_prisma_migrations` without requiring a destructive `prisma migrate reset`.
